"""
MongoDB Utility Class
A production-ready, all-in-one utility for MongoDB CRUD operations,
bulk operations, indexing, TTL, import/export, and secure data hashing.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import secrets
import string
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional, Union

try:
    from bson.objectid import ObjectId
    from pymongo import MongoClient
    from pymongo.collection import Collection
    from pymongo.database import Database
    from pymongo import ASCENDING, DESCENDING
except ImportError:
    raise ImportError("Install pymongo: pip install pymongo")

try:
    import bcrypt
except ImportError:
    raise ImportError("Install bcrypt: pip install bcrypt")


class MongoUtil:
    """
    Production-ready MongoDB utility class for CRUD operations,
    bulk operations, indexing, TTL, import/export, and secure data hashing.

    Attributes:
        connection_string (str): MongoDB connection URI.
        database (str): Active database name.
        collection (str): Active collection name.
        index_key (str): Key segment used in index names.
        default_ttl (Optional[int]): Default TTL in seconds for documents.
    """

    def __init__(
        self,
        database: str,
        collection: str,
        connection_string: str = "mongodb://localhost:27017",
        index_key: str = "IDX",
        default_ttl: Optional[int] = None,
    ) -> None:
        """
        Initialize MongoUtil instance.

        Args:
            database: Database name (required).
            collection: Collection name (required).
            connection_string: MongoDB connection URI.
                              Defaults to localhost:27017.
            index_key: Key segment used in index names. Defaults to "IDX".
            default_ttl: Default TTL in seconds for documents.
                         If set, adds _createdAt field and a TTL index.
                         Pass None to disable (documents live forever).

        Example:
            >>> util = MongoUtil(
            ...     database="myapp",
            ...     collection="users",
            ...     connection_string="mongodb://localhost:27017",
            ...     default_ttl=3600,
            ... )
        """
        self.connection_string: str = connection_string
        self.database: str = database
        self.collection: str = collection
        self.index_key: str = index_key.upper()
        self.default_ttl: Optional[int] = default_ttl
        self._client: MongoClient = MongoClient(self.connection_string)
        self._db: Database = self._client[self.database]
        self._col: Collection = self._db[self.collection]
        self._ttl_index_created: bool = False

    def _ensure_ttl_index(self) -> None:
        """Create TTL index on _createdAt if default_ttl is set and not yet created."""
        if self.default_ttl is not None and not self._ttl_index_created:
            existing_indexes = self._col.index_information()
            ttl_index_name = f"{self.index_key}_createdAt_ttl"
            if ttl_index_name not in existing_indexes:
                self._col.create_index(
                    "_createdAt",
                    name=ttl_index_name,
                    expireAfterSeconds=self.default_ttl,
                )
            self._ttl_index_created = True

    def _add_timestamp(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Add _createdAt timestamp if default_ttl is set."""
        if self.default_ttl is not None:
            self._ensure_ttl_index()
            data = {**data, "_createdAt": datetime.now(timezone.utc)}
        return data

    # ──────────────────────────────────────────────
    # CRUD OPERATIONS
    # ──────────────────────────────────────────────

    def create(
        self,
        data: Dict[str, Any],
        id: Optional[str] = None,
        overwrite: bool = False,
    ) -> str:
        """
        Create a new document or overwrite if overwrite is True.
        If id is not provided, MongoDB auto-generates an ObjectId.

        Args:
            data: Dictionary of fields to store.
            id: Unique identifier for the document. Auto-generated if None.
            overwrite: If True, replace existing document entirely.

        Returns:
            The document id (provided or auto-generated by MongoDB).

        Raises:
            ValueError: If document exists and overwrite is False.
        """
        data = self._add_timestamp(data)
        if id is not None:
            if not overwrite and self._col.find_one({"_id": id}):
                raise ValueError(f"Document '{id}' already exists. Use overwrite=True to update.")
            if overwrite:
                self._col.replace_one({"_id": id}, {**data, "_id": id}, upsert=True)
            else:
                self._col.insert_one({**data, "_id": id})
            return id
        else:
            auto_id = str(ObjectId())
            data["_id"] = auto_id
            self._col.insert_one(data)
            return auto_id

    def read(
        self,
        id: str,
        projection: Optional[Dict[str, int]] = None,
    ) -> Optional[Dict[str, Any]]:
        """
        Read a document by id.

        Args:
            id: Unique identifier for the document.
            projection: Optional field projection.
                       e.g., {"username": 1, "email": 1} to include only these.
                       e.g., {"password": 0} to exclude a field.

        Returns:
            Document dict if found, None otherwise.
        """
        doc = self._col.find_one({"_id": id}, projection=projection)
        if doc and "_id" in doc:
            doc["id"] = doc.pop("_id")
        return doc

    def update(self, id: str, data: Dict[str, Any]) -> bool:
        """
        Update specific fields in an existing document.

        Args:
            id: Unique identifier for the document.
            data: Dictionary of fields to update.

        Returns:
            True if document existed and was updated, False otherwise.
        """
        result = self._col.update_one({"_id": id}, {"$set": data})
        return result.matched_count > 0

    def delete(self, id: str) -> bool:
        """
        Delete a document by id.

        Args:
            id: Unique identifier for the document.

        Returns:
            True if document existed and was deleted, False otherwise.
        """
        result = self._col.delete_one({"_id": id})
        return result.deleted_count > 0

    def delete_fields(self, id: str, *fields: str) -> int:
        """
        Delete specific fields from a document.

        Args:
            id: Unique identifier for the document.
            *fields: Field names to remove.

        Returns:
            Number of documents modified (0 or 1).
        """
        if not fields:
            return 0
        unset_dict = {field: "" for field in fields}
        result = self._col.update_one({"_id": id}, {"$unset": unset_dict})
        return result.modified_count

    def exists(self, id: str) -> bool:
        """Check if a document exists."""
        return self._col.count_documents({"_id": id}, limit=1) > 0

    def field_exists(self, id: str, field: str) -> bool:
        """Check if a specific field exists in a document."""
        doc = self._col.find_one({"_id": id}, {field: 1})
        return doc is not None and field in doc

    def keys(self, id: str) -> List[str]:
        """
        Get all field names in a document.

        Args:
            id: Unique identifier for the document.

        Returns:
            List of field names (excluding _id).
        """
        doc = self._col.find_one({"_id": id})
        if not doc:
            return []
        return [k for k in doc.keys() if k != "_id"]

    def values(self, id: str) -> List[Any]:
        """
        Get all values in a document.

        Args:
            id: Unique identifier for the document.

        Returns:
            List of field values.
        """
        doc = self._col.find_one({"_id": id})
        if not doc:
            return []
        return [v for k, v in doc.items() if k != "_id"]

    def length(self, id: str) -> int:
        """
        Get number of fields in a document (excluding _id).

        Args:
            id: Unique identifier for the document.

        Returns:
            Number of fields.
        """
        doc = self._col.find_one({"_id": id})
        if not doc:
            return 0
        return len([k for k in doc.keys() if k != "_id"])

    def increment(self, id: str, field: str, amount: int = 1) -> int:
        """
        Increment a numeric field value.

        Args:
            id: Unique identifier for the document.
            field: Field name to increment.
            amount: Increment amount (can be negative).

        Returns:
            New value after increment, or -1 if document not found.
        """
        result = self._col.find_one_and_update(
            {"_id": id},
            {"$inc": {field: amount}},
            return_document=True,
        )
        if result and field in result:
            return result[field]
        return -1

    def increment_float(self, id: str, field: str, amount: float = 1.0) -> float:
        """
        Increment a float field value.

        Args:
            id: Unique identifier for the document.
            field: Field name to increment.
            amount: Increment amount (can be negative).

        Returns:
            New value after increment, or -1.0 if document not found.
        """
        result = self._col.find_one_and_update(
            {"_id": id},
            {"$inc": {field: amount}},
            return_document=True,
        )
        if result and field in result:
            return float(result[field])
        return -1.0

    # ──────────────────────────────────────────────
    # SET IF NOT EXISTS / GET OR CREATE
    # ──────────────────────────────────────────────

    def set_if_not_exists(self, id: str, field: str, value: Any) -> bool:
        """
        Atomically set a field only if it does not already exist in the document.
        Creates the document with the field if document does not exist.

        Args:
            id: Unique identifier for the document.
            field: Field name to set.
            value: Value to set.

        Returns:
            True if field was set (did not exist), False if already present.
        """
        result = self._col.update_one(
            {"_id": id, field: {"$exists": False}},
            {"$set": {field: value}},
            upsert=True,
        )
        return result.modified_count > 0 or result.upserted_id is not None

    def get_or_create(
        self,
        id: str,
        data: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Return existing document data, or create it and return the new data.

        Args:
            id: Unique identifier for the document.
            data: Dictionary to store if document does not exist.

        Returns:
            The document data (existing or newly created).
        """
        doc = self._col.find_one({"_id": id})
        if doc:
            result = {k: v for k, v in doc.items() if k != "_id"}
            result["id"] = id
            return result
        data = self._add_timestamp(data)
        self._col.insert_one({**data, "_id": id})
        data["id"] = id
        return data

    # ──────────────────────────────────────────────
    # TTL OPERATIONS
    # ──────────────────────────────────────────────

    def _resolve_ttl(self, seconds: int) -> int:
        """
        Resolve the effective TTL index seconds to use for _createdAt adjustment.
        When default_ttl is set, uses it. Otherwise looks up or creates a TTL index.
        """
        if self.default_ttl is not None:
            return self.default_ttl
        ttl_index_name = f"{self.index_key}_createdAt_ttl"
        existing = self._col.index_information()
        for name, info in existing.items():
            if info.get("key") == [("_createdAt", 1)] and "expireAfterSeconds" in info:
                return info["expireAfterSeconds"]
        self._col.create_index(
            "_createdAt",
            name=ttl_index_name,
            expireAfterSeconds=seconds,
        )
        return seconds

    def expire(self, id: str, seconds: int) -> bool:
        """
        Set/reset TTL on a document by updating its _createdAt.

        Args:
            id: Unique identifier for the document.
            seconds: Desired remaining TTL in seconds.

        Returns:
            True if updated, False if document not found.
        """
        index_ttl = self._resolve_ttl(seconds)
        delta = index_ttl - seconds
        new_time = datetime.now(timezone.utc) - timedelta(seconds=delta)
        result = self._col.update_one(
            {"_id": id},
            {"$set": {"_createdAt": new_time}},
        )
        return result.matched_count > 0

    def bulk_expire(self, ids: List[str], seconds: int) -> int:
        """
        Set/reset TTL on multiple documents.

        Args:
            ids: List of document identifiers.
            seconds: Desired remaining TTL in seconds.

        Returns:
            Number of documents updated.
        """
        if not ids:
            return 0
        index_ttl = self._resolve_ttl(seconds)
        delta = index_ttl - seconds
        new_time = datetime.now(timezone.utc) - timedelta(seconds=delta)
        result = self._col.update_many(
            {"_id": {"$in": ids}},
            {"$set": {"_createdAt": new_time}},
        )
        return result.modified_count

    def persist(self, id: str) -> bool:
        """
        Remove TTL from a document by removing _createdAt field.

        Args:
            id: Unique identifier for the document.

        Returns:
            True if TTL was removed, False otherwise.
        """
        result = self._col.update_one(
            {"_id": id},
            {"$unset": {"_createdAt": ""}},
        )
        return result.modified_count > 0

    # ──────────────────────────────────────────────
    # COPY / RENAME OPERATIONS
    # ──────────────────────────────────────────────

    def copy(
        self,
        source_id: str,
        dest_id: Optional[str] = None,
        overwrite: bool = False,
    ) -> str:
        """
        Copy a document to a new id.
        If dest_id is not provided, MongoDB auto-generates an ObjectId.

        Args:
            source_id: Source document identifier.
            dest_id: Destination document identifier. Auto-generated if None.
            overwrite: If True, overwrite existing destination.

        Returns:
            The destination id (provided or auto-generated).

        Raises:
            ValueError: If destination exists and overwrite is False.
        """
        data = self.read(source_id)
        if data is None:
            return ""
        clean = {k: v for k, v in data.items() if k != "id"}
        return self.create(clean, id=dest_id, overwrite=overwrite)

    def bulk_copy(
        self,
        copies: Dict[str, str],
        overwrite: bool = False,
    ) -> Dict[str, str]:
        """
        Copy multiple documents using bulk operations.

        Args:
            copies: Dict mapping source_id -> dest_id.
            overwrite: If True, overwrite existing destinations.

        Returns:
            Dict mapping destination ids to themselves.
        """
        if not copies:
            return {}
        source_ids = list(copies.keys())
        bulk_data = self.bulk_read(source_ids)
        new_entries: Dict[str, Dict[str, Any]] = {}
        for src_id, dest_id in copies.items():
            data = bulk_data.get(src_id)
            if data is not None:
                new_entries[dest_id] = {k: v for k, v in data.items() if k != "id"}
        if not new_entries:
            return {}
        return self.bulk_create(new_entries, overwrite=overwrite)

    def rename(self, old_id: str, new_id: str, overwrite: bool = False) -> bool:
        """
        Rename a document by copying to new id and deleting old.

        Args:
            old_id: Current document identifier.
            new_id: New document identifier.
            overwrite: If True, overwrite if new_id already exists.

        Returns:
            True if rename succeeded.

        Raises:
            ValueError: If new_id exists and overwrite is False.
        """
        if not self.exists(old_id):
            return False
        if not overwrite and self.exists(new_id):
            raise ValueError(f"Document '{new_id}' already exists. Use overwrite=True.")
        data = self.read(old_id)
        if data is None:
            return False
        clean_data = {k: v for k, v in data.items() if k != "id"}
        if overwrite:
            self._col.replace_one({"_id": new_id}, {**clean_data, "_id": new_id}, upsert=True)
        else:
            self._col.insert_one({**clean_data, "_id": new_id})
        self._col.delete_one({"_id": old_id})
        return True

    # ──────────────────────────────────────────────
    # SEARCH OPERATIONS
    # ──────────────────────────────────────────────

    def search(
        self,
        field: str,
        value: Any,
        exact: bool = True,
    ) -> List[str]:
        """
        Search documents where a field matches a value.

        Args:
            field: Field name to match against.
            value: Value to search for.
            exact: If True, exact match. If False and value is string,
                   performs substring match (case-insensitive).

        Returns:
            List of matching document ids.
        """
        if exact:
            cursor = self._col.find({field: value}, {"_id": 1})
        else:
            if not isinstance(value, str):
                value = str(value)
            cursor = self._col.find(
                {field: {"$regex": value, "$options": "i"}},
                {"_id": 1},
            )
        return [doc["_id"] for doc in cursor]

    def search_with_data(
        self,
        field: str,
        value: Any,
        exact: bool = True,
    ) -> Dict[str, Dict[str, Any]]:
        """
        Search documents with full data where a field matches a value.

        Args:
            field: Field name to match against.
            value: Value to search for.
            exact: If True, exact match. If False, substring match.

        Returns:
            Dict of matching documents with their data.
        """
        if exact:
            cursor = self._col.find({field: value})
        else:
            if not isinstance(value, str):
                value = str(value)
            cursor = self._col.find({field: {"$regex": value, "$options": "i"}})
        result: Dict[str, Dict[str, Any]] = {}
        for doc in cursor:
            doc_id = doc.pop("_id")
            result[doc_id] = doc
        return result

    def search_many(self, query: Dict[str, Any]) -> List[str]:
        """
        Search documents using a MongoDB query dict.

        Args:
            query: MongoDB query filter.
                   e.g., {"age": {"$gte": 18}, "status": "active"}

        Returns:
            List of matching document ids.
        """
        cursor = self._col.find(query, {"_id": 1})
        return [doc["_id"] for doc in cursor]

    def search_many_with_data(self, query: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
        """
        Search documents with full data using a MongoDB query dict.

        Args:
            query: MongoDB query filter.

        Returns:
            Dict of matching documents with their data.
        """
        cursor = self._col.find(query)
        result: Dict[str, Dict[str, Any]] = {}
        for doc in cursor:
            doc_id = doc.pop("_id")
            result[doc_id] = doc
        return result

    # ──────────────────────────────────────────────
    # BULK OPERATIONS
    # ──────────────────────────────────────────────

    def bulk_create(
        self,
        entries: Union[Dict[str, Dict[str, Any]], List[Dict[str, Any]]],
        overwrite: bool = False,
    ) -> Union[Dict[str, str], List[str]]:
        """
        Create multiple documents. Supports both dict (with ids) and list (auto-id) input.

        Args:
            entries: Dict mapping ids to data dicts, OR list of data dicts (auto-id).
            overwrite: If True, replace existing documents.

        Returns:
            List of generated ids if list input, Dict mapping ids to themselves if dict input.
        """
        if not entries:
            return [] if isinstance(entries, list) else {}
        if isinstance(entries, list):
            docs = []
            ids: List[str] = []
            for d in entries:
                data = self._add_timestamp(dict(d))
                doc_id = str(ObjectId())
                data["_id"] = doc_id
                docs.append(data)
                ids.append(doc_id)
            self._col.insert_many(docs, ordered=False)
            return ids
        ids_map: Dict[str, str] = {}
        if overwrite:
            from pymongo import ReplaceOne
            ops = []
            for doc_id, data in entries.items():
                data = self._add_timestamp(data)
                ops.append(ReplaceOne(
                    {"_id": doc_id},
                    {**data, "_id": doc_id},
                    upsert=True,
                ))
                ids_map[doc_id] = doc_id
            self._col.bulk_write(ops, ordered=False)
            return ids_map
        else:
            docs = []
            for doc_id, data in entries.items():
                data = self._add_timestamp(data)
                docs.append({**data, "_id": doc_id})
                ids_map[doc_id] = doc_id
            self._col.insert_many(docs, ordered=False)
            return ids_map

    def bulk_read(self, ids: List[str]) -> Dict[str, Optional[Dict[str, Any]]]:
        """
        Read multiple documents by their ids.

        Args:
            ids: List of document identifiers.

        Returns:
            Dict mapping ids to their data (or None if not found).
        """
        if not ids:
            return {}
        cursor = self._col.find({"_id": {"$in": ids}})
        found: Dict[str, Dict[str, Any]] = {}
        for doc in cursor:
            doc_id = doc.pop("_id")
            found[doc_id] = doc
        return {doc_id: found.get(doc_id) for doc_id in ids}

    def bulk_update(self, updates: Dict[str, Dict[str, Any]]) -> int:
        """
        Update multiple documents.

        Args:
            updates: Dict mapping ids to their update data.

        Returns:
            Number of documents updated.
        """
        if not updates:
            return 0
        from pymongo import UpdateOne
        ops = [
            UpdateOne({"_id": doc_id}, {"$set": data})
            for doc_id, data in updates.items()
        ]
        result = self._col.bulk_write(ops, ordered=False)
        return result.modified_count

    def bulk_delete(self, ids: List[str]) -> int:
        """
        Delete multiple documents by their ids.

        Args:
            ids: List of document identifiers to delete.

        Returns:
            Number of documents deleted.
        """
        if not ids:
            return 0
        result = self._col.delete_many({"_id": {"$in": ids}})
        return result.deleted_count

    def get_all(
        self,
        query: Optional[Dict[str, Any]] = None,
        sort_by: Optional[str] = None,
        sort_order: Literal[1, -1] = ASCENDING,
        skip: int = 0,
        limit: int = 0,
    ) -> Dict[str, Dict[str, Any]]:
        """
        Get documents matching an optional query with pagination, sorting, and filtering.

        Args:
            query: Optional MongoDB query filter. If None, returns all documents.
                   e.g., {"status": "active", "age": {"$gte": 18}}
            sort_by: Optional field name to sort by.
            sort_order: Sort direction. ASCENDING (1) or DESCENDING (-1).
            skip: Number of documents to skip (for pagination).
            limit: Maximum number of documents to return. 0 = no limit.

        Returns:
            Dict mapping document ids to their data.
        """
        filter_q = query if query is not None else {}
        cursor = self._col.find(filter_q)
        if sort_by is not None:
            cursor = cursor.sort(sort_by, sort_order)
        if skip > 0:
            cursor = cursor.skip(skip)
        if limit > 0:
            cursor = cursor.limit(limit)
        result: Dict[str, Dict[str, Any]] = {}
        for doc in cursor:
            doc_id = doc.pop("_id")
            result[doc_id] = doc
        return result

    def delete_all(self, query: Optional[Dict[str, Any]] = None) -> int:
        """
        Delete documents matching an optional query.

        Args:
            query: Optional MongoDB query filter. If None, deletes all documents.

        Returns:
            Number of documents deleted.
        """
        filter_q = query if query is not None else {}
        result = self._col.delete_many(filter_q)
        return result.deleted_count

    def count_all(self, query: Optional[Dict[str, Any]] = None) -> int:
        """
        Count documents matching an optional query.

        Args:
            query: Optional MongoDB query filter. If None, counts all.

        Returns:
            Number of matching documents.
        """
        filter_q = query if query is not None else {}
        return self._col.count_documents(filter_q)

    def list_ids(
        self,
        query: Optional[Dict[str, Any]] = None,
        skip: int = 0,
        limit: int = 0,
    ) -> List[str]:
        """
        List document ids matching an optional query with pagination.

        Args:
            query: Optional MongoDB query filter.
            skip: Number of ids to skip (for pagination).
            limit: Maximum ids to return. 0 = no limit.

        Returns:
            List of document ids.
        """
        filter_q = query if query is not None else {}
        cursor = self._col.find(filter_q, {"_id": 1})
        if skip > 0:
            cursor = cursor.skip(skip)
        if limit > 0:
            cursor = cursor.limit(limit)
        return [doc["_id"] for doc in cursor]

    # ──────────────────────────────────────────────
    # INDEX OPERATIONS
    # ──────────────────────────────────────────────

    def create_index(
        self,
        field: str,
        unique: bool = False,
        descending: bool = False,
    ) -> str:
        """
        Create an index on a field.

        Args:
            field: Field name to index.
            unique: If True, create a unique index.
            descending: If True, descending order. Default ascending.

        Returns:
            Name of the created index.
        """
        direction = DESCENDING if descending else ASCENDING
        index_name = self._col.create_index(
            [(field, direction)],
            unique=unique,
            name=f"{self.index_key}_{field}",
        )
        return index_name

    def find_by_index(self, field: str, value: Any) -> List[str]:
        """
        Find document ids by indexed field value.

        Args:
            field: Indexed field name.
            value: Value to search for.

        Returns:
            List of matching document ids.
        """
        cursor = self._col.find({field: value}, {"_id": 1})
        return [doc["_id"] for doc in cursor]

    def find_by_index_with_data(self, field: str, value: Any) -> Dict[str, Dict[str, Any]]:
        """
        Find documents with data by indexed field value.

        Args:
            field: Indexed field name.
            value: Value to search for.

        Returns:
            Dict of matching documents with their data.
        """
        cursor = self._col.find({field: value})
        result: Dict[str, Dict[str, Any]] = {}
        for doc in cursor:
            doc_id = doc.pop("_id")
            result[doc_id] = doc
        return result

    def drop_index(self, field: str) -> None:
        """
        Drop index on a field.

        Args:
            field: Field name whose index to drop.
        """
        index_name = f"{self.index_key}_{field}"
        try:
            self._col.drop_index(index_name)
        except Exception:
            pass

    def list_indexes(self) -> List[str]:
        """
        List all index names on the collection.

        Returns:
            List of index names.
        """
        return list(self._col.index_information().keys())

    # ──────────────────────────────────────────────
    # ADMIN OPERATIONS
    # ──────────────────────────────────────────────

    @staticmethod
    def list_databases(connection_string: str = "mongodb://localhost:27017") -> List[str]:
        """
        List all databases on the server.

        Args:
            connection_string: MongoDB connection URI.

        Returns:
            List of database names.
        """
        client = MongoClient(connection_string)
        names = client.list_database_names()
        client.close()
        return names

    @staticmethod
    def count_databases(connection_string: str = "mongodb://localhost:27017") -> int:
        """
        Count all databases on the server.

        Args:
            connection_string: MongoDB connection URI.

        Returns:
            Number of databases.
        """
        return len(MongoUtil.list_databases(connection_string))

    def list_collections(self, database: Optional[str] = None) -> List[str]:
        """
        List all collections in a database.

        Args:
            database: Database name. If None, uses the current database.

        Returns:
            List of collection names.
        """
        db = self._client[database] if database else self._db
        return db.list_collection_names()

    def count_collections(self, database: Optional[str] = None) -> int:
        """
        Count all collections in a database.

        Args:
            database: Database name. If None, uses the current database.

        Returns:
            Number of collections.
        """
        return len(self.list_collections(database=database))

    def count_documents_in_collection(
        self,
        database: Optional[str] = None,
        collection: Optional[str] = None,
    ) -> int:
        """
        Count all documents in a collection.

        Args:
            database: Database name. If None, uses the current database.
            collection: Collection name. If None, uses the current collection.

        Returns:
            Number of documents.
        """
        if database or collection:
            db_name = database or self.database
            col_name = collection or self.collection
            return self._client[db_name][col_name].estimated_document_count()
        return self._col.estimated_document_count()

    def drop_collection(self, collection: Optional[str] = None) -> None:
        """
        Drop a collection. Irreversible — all documents and indexes are removed.

        Args:
            collection: Collection name to drop. If None, drops the current collection.
        """
        col_name = collection or self.collection
        self._db.drop_collection(col_name)

    def drop_database(self, database: Optional[str] = None) -> None:
        """
        Drop a database. Irreversible — all collections and documents are removed.

        Args:
            database: Database name to drop. If None, drops the current database.
        """
        db_name = database or self.database
        self._client.drop_database(db_name)

    def remove_duplicates(
        self,
        query: Optional[Dict[str, Any]] = None,
        keep: Literal["first", "last"] = "first",
        dry_run: bool = False,
    ) -> Dict[str, Any]:
        """
        Remove duplicate documents based on matching field values.

        Args:
            query: Dict of fields to compare for duplicates.
                   {} or None means all fields (excluding _id)
                   must match to be considered duplicates.
                   e.g., {"email": 1} groups by the email field.
                   e.g., {"email": 1, "name": 1} groups by email + name.
            keep: Which duplicate to keep — "first" (earliest _id) or "last" (latest).
            dry_run: If True, only report duplicates without deleting.

        Returns:
            Dict with duplicate_groups, total_duplicates, to_delete, deleted, kept.
        """
        to_delete: List[Any] = []
        groups = 0
        total_dups = 0

        if query:
            group_id = {f: f"${f}" for f in query}
            pipeline = [
                {"$group": {"_id": group_id, "ids": {"$push": "$_id"}, "count": {"$sum": 1}}},
                {"$match": {"count": {"$gt": 1}}},
            ]
            for group in self._col.aggregate(pipeline):
                groups += 1
                ids = group["ids"]
                total_dups += len(ids)
                ids.sort(key=lambda x: ObjectId(x).generation_time if isinstance(x, str) and len(x) == 24 else 0)
                to_delete.extend(ids[1:] if keep == "first" else ids[:-1])
        else:
            docs = list(self._col.find().sort("_id", 1 if keep == "first" else -1))
            seen: List[Any] = []
            for doc in docs:
                doc_id = doc.pop("_id", None)
                content = sorted((k, v) for k, v in doc.items())
                if content in seen:
                    to_delete.append(doc_id)
                    total_dups += 1
                else:
                    seen.append(content)
                    groups += 1
            total_dups += groups

        result: Dict[str, Any] = {
            "duplicate_groups": groups,
            "total_duplicates": total_dups,
            "to_delete": len(to_delete),
            "kept": groups,
        }

        if dry_run or not to_delete:
            result["deleted"] = 0
            return result

        delete_result = self._col.delete_many({"_id": {"$in": to_delete}})
        result["deleted"] = delete_result.deleted_count
        return result

    # ──────────────────────────────────────────────
    # IMPORT / EXPORT — JSON
    # ──────────────────────────────────────────────

    def export_json(
        self,
        filepath: str,
        query: Optional[Dict[str, Any]] = None,
        indent: int = 2,
    ) -> int:
        """
        Export documents to a JSON file.

        Args:
            filepath: Path to output JSON file.
            query: Optional MongoDB query filter.
            indent: JSON indentation level.

        Returns:
            Number of documents exported.
        """
        data = self.get_all(query=query)
        export_data = {
            "database": self.database,
            "collection": self.collection,
            "documents": data,
        }
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(export_data, f, indent=indent, ensure_ascii=False, default=str)
        return len(data)

    def import_json(
        self,
        filepath: str,
        overwrite: bool = False,
    ) -> int:
        """
        Import documents from a JSON file.

        Args:
            filepath: Path to input JSON file.
            overwrite: If True, overwrite existing documents.

        Returns:
            Number of documents imported.
        """
        with open(filepath, "r", encoding="utf-8") as f:
            import_data = json.load(f)
        entries = import_data.get("documents", {})
        return len(self.bulk_create(entries, overwrite=overwrite))

    def export_json_string(
        self,
        query: Optional[Dict[str, Any]] = None,
        indent: int = 2,
    ) -> str:
        """
        Export documents to a JSON string.

        Args:
            query: Optional MongoDB query filter.
            indent: JSON indentation level.

        Returns:
            JSON string of all documents.
        """
        data = self.get_all(query=query)
        export_data = {
            "database": self.database,
            "collection": self.collection,
            "documents": data,
        }
        return json.dumps(export_data, indent=indent, ensure_ascii=False, default=str)

    def import_json_string(
        self,
        json_str: str,
        overwrite: bool = False,
    ) -> int:
        """
        Import documents from a JSON string.

        Args:
            json_str: JSON string containing documents.
            overwrite: If True, overwrite existing documents.

        Returns:
            Number of documents imported.
        """
        import_data = json.loads(json_str)
        entries = import_data.get("documents", {})
        return len(self.bulk_create(entries, overwrite=overwrite))

    # ──────────────────────────────────────────────
    # IMPORT / EXPORT — CSV
    # ──────────────────────────────────────────────

    def export_csv(
        self,
        filepath: str,
        query: Optional[Dict[str, Any]] = None,
        id_column: str = "_id",
    ) -> int:
        """
        Export documents to a CSV file.

        Args:
            filepath: Path to output CSV file.
            query: Optional MongoDB query filter.
            id_column: Column name for document id. Defaults to "_id".

        Returns:
            Number of documents exported.
        """
        data = self.get_all(query=query)
        if not data:
            path = Path(filepath)
            path.parent.mkdir(parents=True, exist_ok=True)
            with open(path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow([id_column])
            return 0

        all_fields: set[str] = set()
        for entry in data.values():
            all_fields.update(entry.keys())
        fieldnames = [id_column] + sorted(all_fields)

        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for doc_id, doc_data in data.items():
                row = {id_column: doc_id}
                row.update({k: str(v) for k, v in doc_data.items()})
                writer.writerow(row)
        return len(data)

    def import_csv(
        self,
        filepath: str,
        id_column: str = "_id",
        overwrite: bool = False,
    ) -> int:
        """
        Import documents from a CSV file.

        Args:
            filepath: Path to input CSV file.
            id_column: Column name that contains document id.
            overwrite: If True, overwrite existing documents.

        Returns:
            Number of documents imported.

        Raises:
            ValueError: If id_column is not found in CSV headers.
        """
        with open(filepath, "r", newline="", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            if reader.fieldnames is None or id_column not in reader.fieldnames:
                raise ValueError(f"Column '{id_column}' not found in CSV headers: {reader.fieldnames}")
            entries: Dict[str, Dict[str, str]] = {}
            for row in reader:
                doc_id = row.pop(id_column)
                entries[doc_id] = {k: v for k, v in row.items() if v}
        return len(self.bulk_create(entries, overwrite=overwrite))

    def export_csv_string(
        self,
        query: Optional[Dict[str, Any]] = None,
        id_column: str = "_id",
    ) -> str:
        """
        Export documents to a CSV string.

        Args:
            query: Optional MongoDB query filter.
            id_column: Column name for document id.

        Returns:
            CSV string of all documents.
        """
        data = self.get_all(query=query)
        all_fields: set[str] = set()
        for entry in data.values():
            all_fields.update(entry.keys())
        fieldnames = [id_column] + sorted(all_fields)

        output = io.StringIO()
        writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        for doc_id, doc_data in data.items():
            row = {id_column: doc_id}
            row.update({k: str(v) for k, v in doc_data.items()})
            writer.writerow(row)
        return output.getvalue()

    # ──────────────────────────────────────────────
    # SWITCH OPERATIONS
    # ──────────────────────────────────────────────

    def switch_database(self, database: str) -> MongoUtil:
        """
        Return a new MongoUtil instance with a different database.
        Keeps the same collection, connection, index_key, and default_ttl.

        Args:
            database: New database name.

        Returns:
            New MongoUtil instance.
        """
        return MongoUtil(
            database=database,
            collection=self.collection,
            connection_string=self.connection_string,
            index_key=self.index_key,
            default_ttl=self.default_ttl,
        )

    def switch_collection(self, collection: str) -> MongoUtil:
        """
        Return a new MongoUtil instance with a different collection.
        Keeps the same database, connection, index_key, and default_ttl.

        Args:
            collection: New collection name.

        Returns:
            New MongoUtil instance.
        """
        return MongoUtil(
            database=self.database,
            collection=collection,
            connection_string=self.connection_string,
            index_key=self.index_key,
            default_ttl=self.default_ttl,
        )

    def switch(self, database: Optional[str] = None, collection: Optional[str] = None) -> MongoUtil:
        """
        Return a new MongoUtil instance with different database and/or collection.

        Args:
            database: New database name. If None, keeps current.
            collection: New collection name. If None, keeps current.

        Returns:
            New MongoUtil instance.
        """
        return MongoUtil(
            database=database or self.database,
            collection=collection or self.collection,
            connection_string=self.connection_string,
            index_key=self.index_key,
            default_ttl=self.default_ttl,
        )

    # ──────────────────────────────────────────────
    # STATIC UTILITY METHODS
    # ──────────────────────────────────────────────

    @staticmethod
    def generate_random_string(length: int = 32, charset: str = string.ascii_letters + string.digits) -> str:
        """
        Generate a cryptographically secure random alphanumeric string.

        Args:
            length: Length of the string to generate. Defaults to 32.
            charset: Character set to use. Defaults to alphanumeric.

        Returns:
            Random string of specified length.
        """
        return "".join(secrets.choice(charset) for _ in range(length))

    @staticmethod
    def generate_random_number(length: int = 6) -> str:
        """
        Generate a cryptographically secure random numeric string.
        Useful for OTPs, PINs, and verification codes.

        Args:
            length: Number of digits. Defaults to 6.

        Returns:
            Random numeric string of specified length.
        """
        return "".join(secrets.choice(string.digits) for _ in range(length))

    @staticmethod
    def generate_token(length: int = 64) -> str:
        """
        Generate a cryptographically secure URL-safe token.

        Args:
            length: Byte length before encoding. Defaults to 64.

        Returns:
            URL-safe token string.
        """
        return secrets.token_urlsafe(length)

    @staticmethod
    def generate_uuid4() -> str:
        """Generate a random UUID4."""
        return str(uuid.uuid4())

    @staticmethod
    def generate_uuid5(namespace: str, name: str) -> str:
        """
        Generate a deterministic UUID5 from namespace and name.

        Args:
            namespace: Namespace string (e.g., "myapp.users").
            name: Name to hash within the namespace.

        Returns:
            UUID5 string.
        """
        ns_uuid = uuid.uuid5(uuid.NAMESPACE_DNS, namespace)
        return str(uuid.uuid5(ns_uuid, name))

    @staticmethod
    def hash_password(password: str) -> str:
        """
        Hash a password using bcrypt.

        Args:
            password: Plain text password to hash.

        Returns:
            Bcrypt hashed password string.
        """
        salt = bcrypt.gensalt(rounds=12)
        return bcrypt.hashpw(password.encode("utf-8"), salt).decode("utf-8")

    @staticmethod
    def verify_password(password: str, hashed: str) -> bool:
        """
        Verify a password against its bcrypt hash.

        Args:
            password: Plain text password to verify.
            hashed: Bcrypt hashed password to verify against.

        Returns:
            True if password matches, False otherwise.
        """
        return bcrypt.checkpw(password.encode("utf-8"), hashed.encode("utf-8"))

    @staticmethod
    def hash_sensitive_data(data: str, pepper: str = "") -> str:
        """
        Hash sensitive data (emails, PII) using SHA-256.

        Args:
            data: Sensitive data to hash.
            pepper: Optional application-level pepper.

        Returns:
            Hex digest of hashed data.
        """
        salted = f"{pepper}{data}".encode("utf-8")
        return hashlib.sha256(salted).hexdigest()

    @staticmethod
    def hash_sensitive_data_hmac(data: str, secret: str) -> str:
        """
        Hash sensitive data using HMAC-SHA256.

        Args:
            data: Sensitive data to hash.
            secret: Secret key for HMAC.

        Returns:
            Hex digest of HMAC hash.
        """
        return hashlib.new("sha256", f"{secret}{data}".encode("utf-8"), usedforsecurity=True).hexdigest()

    @staticmethod
    def generate_hash_id(data: Dict[str, Any]) -> str:
        """
        Generate a deterministic hash ID from a data dictionary.
        Useful for deduplication.

        Args:
            data: Dictionary to hash.

        Returns:
            16-character hash ID.
        """
        canonical = str(sorted(data.items()))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]

    # ──────────────────────────────────────────────
    # LIFECYCLE
    # ──────────────────────────────────────────────

    def close(self) -> None:
        """Close MongoDB connection."""
        self._client.close()

    def __repr__(self) -> str:
        """String representation of MongoUtil."""
        return (
            f"MongoUtil(connection='{self.connection_string}', "
            f"db='{self.database}', col='{self.collection}', "
            f"index_key='{self.index_key}', default_ttl={self.default_ttl})"
        )

    def __enter__(self) -> "MongoUtil":
        """Context manager entry."""
        return self

    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Context manager exit - close connection."""
        self.close()


# ──────────────────────────────────────────────
# USAGE EXAMPLES
# ──────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("MongoUtil - Usage Examples")
    print("=" * 60)

    # Initialize
    users = MongoUtil(
        database="myapp",
        collection="users",
        connection_string="mongodb://localhost:27017",
        index_key="INDEX",
        default_ttl=None,  # No TTL for persistent data
    )

    # ── STATIC UTILITIES ──────────────────────

    print("\n--- Static Utilities ---")
    print(f"Random string (16): {MongoUtil.generate_random_string(16)}")
    print(f"Random string (32): {MongoUtil.generate_random_string(32)}")
    print(f"OTP (6 digits):     {MongoUtil.generate_random_number(6)}")
    print(f"PIN (4 digits):     {MongoUtil.generate_random_number(4)}")
    print(f"Token:              {MongoUtil.generate_token(32)}")
    print(f"UUID4:              {MongoUtil.generate_uuid4()}")
    print(f"UUID5:              {MongoUtil.generate_uuid5('myapp.users', 'john@example.com')}")

    # Password hashing
    password = "SuperSecret123!"
    hashed_pw = MongoUtil.hash_password(password)
    print(f"Hashed password:    {hashed_pw[:30]}...")
    print(f"Password verified:  {MongoUtil.verify_password(password, hashed_pw)}")

    # Sensitive data hashing
    email = "user@example.com"
    email_hash = MongoUtil.hash_sensitive_data(email, pepper="myapp")
    print(f"Hashed email:       {email_hash}")

    # ── CRUD OPERATIONS ───────────────────────

    print("\n--- CRUD Operations ---")
    users.delete_all()

    # Create
    user_id = users.create({
        "username": "johndoe",
        "email": "john@example.com",
        "role": "admin",
        "status": "active",
    })
    print(f"Created user: {user_id}")

    # Auto-generated id example
    auto_id = users.create({"username": "autouser", "status": "pending"})
    print(f"Auto-generated id: {auto_id}")

    # Read
    user_data = users.read(user_id)
    print(f"Read user: {user_data}")

    # Read with projection
    email_only = users.read(user_id, projection={"email": 1})
    print(f"Email only: {email_only}")

    # Update
    users.update(user_id, {"role": "superadmin", "last_login": "2026-01-15"})
    print(f"Updated user: {users.read(user_id)}")

    # Exists
    print(f"User exists: {users.exists(user_id)}")
    print(f"Field exists: {users.field_exists(user_id, 'email')}")

    # Keys, Values, Length
    print(f"Fields: {users.keys(user_id)}")
    print(f"Field count: {users.length(user_id)}")

    # Increment
    users.create({"login_count": 0}, id=user_id + "_stats", overwrite=True)
    users.increment(user_id + "_stats", "login_count", 5)
    print(f"Login count: {users.read(user_id + '_stats')}")

    # Delete specific fields
    users.delete_fields(user_id, "last_login")
    print(f"After field delete: {users.read(user_id)}")

    # Set if not exists
    result1 = users.set_if_not_exists(user_id, "created_at", "2026-01-01")
    result2 = users.set_if_not_exists(user_id, "created_at", "2026-06-01")
    print(f"set_if_not_exists (first):  {result1}")
    print(f"set_if_not_exists (second): {result2}")

    # Get or create
    new_id = MongoUtil.generate_uuid4()
    got = users.get_or_create(new_id, {"username": "newuser", "status": "pending"})
    print(f"get_or_create: {got}")
    got_again = users.get_or_create(new_id, {"username": "shouldnotchange", "status": "nope"})
    print(f"get_or_create (existing): {got_again}")

    # ── BULK OPERATIONS ──────────────────────

    print("\n--- Bulk Operations ---")
    users.delete_all()

    bulk_users = {
        MongoUtil.generate_uuid4(): {"username": f"user_{i}", "status": "active"}
        for i in range(5)
    }
    created = users.bulk_create(bulk_users)
    print(f"Bulk created: {created} entries")

    # Bulk read
    all_ids = list(bulk_users.keys())
    bulk_data = users.bulk_read(all_ids)
    print(f"Bulk read: {len(bulk_data)} entries")

    # Bulk update
    updates = {doc_id: {"status": "inactive"} for doc_id in all_ids[:2]}
    updated = users.bulk_update(updates)
    print(f"Bulk updated: {updated} entries")

    # Bulk delete
    deleted = users.bulk_delete(all_ids[:2])
    print(f"Bulk deleted: {deleted} entries")

    # Get all
    all_data = users.get_all()
    print(f"Total entries: {len(all_data)}")

    # Count all
    count = users.count_all()
    print(f"Entry count: {count}")

    # List all ids
    id_list = users.list_ids()
    print(f"All IDs: {len(id_list)} entries")

    # ── COPY / RENAME ─────────────────────────

    print("\n--- Copy / Rename ---")
    remaining_ids = users.list_ids()
    if remaining_ids:
        src = remaining_ids[0]
        # Copy
        users.copy(src, src + "_copy", overwrite=True)
        print(f"Copied '{src}' -> '{src}_copy'")

        # Bulk copy
        copies = {doc_id: f"{doc_id}_backup" for doc_id in remaining_ids}
        copied = users.bulk_copy(copies, overwrite=True)
        print(f"Bulk copied: {copied} entries")

        # Rename
        users.rename(src + "_copy", src + "_renamed")
        print(f"Renamed '{src}_copy' -> '{src}_renamed'")

    # ── SEARCH ────────────────────────────────

    print("\n--- Search Operations ---")
    users.delete_all()
    users.create({"username": "alice", "role": "admin", "age": 30}, id="u1", overwrite=True)
    users.create({"username": "bob", "role": "user", "age": 25}, id="u2", overwrite=True)
    users.create({"username": "charlie", "role": "admin", "age": 35}, id="u3", overwrite=True)

    # Exact search
    admins = users.search("role", "admin")
    print(f"Admins (exact): {admins}")

    # Substring search
    ali = users.search("username", "ali", exact=False)
    print(f"Username contains 'ali': {ali}")

    # Search with data
    admins_data = users.search_with_data("role", "admin")
    print(f"Admins with data: {list(admins_data.keys())}")

    # MongoDB query search
    young_admins = users.search_many({"role": "admin", "age": {"$lt": 35}})
    print(f"Admins under 35: {young_admins}")

    # ── PAGINATION / SORT / FILTER ────────────

    print("\n--- Pagination / Sort / Filter ---")
    users.delete_all()
    users.create({"username": "zara", "role": "admin", "age": 30}, id="u1")
    users.create({"username": "alice", "role": "user", "age": 25}, id="u2")
    users.create({"username": "mike", "role": "admin", "age": 35}, id="u3")
    users.create({"username": "bob", "role": "user", "age": 28}, id="u4")

    # Sort (ascending)
    sorted_asc = users.get_all(sort_by="username", sort_order=1)
    print(f"Sorted asc: {list(sorted_asc.keys())}")

    # Sort (descending)
    sorted_desc = users.get_all(sort_by="username", sort_order=-1)
    print(f"Sorted desc: {list(sorted_desc.keys())}")

    # Pagination (skip + limit)
    page1 = users.get_all(sort_by="username", skip=0, limit=2)
    print(f"Page 1 (limit 2): {list(page1.keys())}")
    page2 = users.get_all(sort_by="username", skip=2, limit=2)
    print(f"Page 2 (limit 2): {list(page2.keys())}")

    # Query filter + Sort + Pagination
    filtered_page = users.get_all(
        query={"role": "user"},
        sort_by="username",
        sort_order=-1,
        skip=0,
        limit=1,
    )
    print(f"Filtered + sorted + paginated: {list(filtered_page.keys())}")

    # List IDs with pagination
    ids_page = users.list_ids(skip=1, limit=2)
    print(f"list_ids(skip=1, limit=2): {ids_page}")

    # ── ADMIN OPERATIONS ─────────────────────

    print("\n--- Admin Operations ---")
    print(f"Collections: {users.list_collections()}")
    print(f"Collection count: {users.count_collections()}")
    print(f"Doc count in users: {users.count_documents_in_collection()}")

    # ── INDEX OPERATIONS ─────────────────────

    print("\n--- Index Operations ---")
    users.create_index("role")
    users.create_index("username", unique=True)
    print(f"Indexes: {users.list_indexes()}")

    indexed_admins = users.find_by_index("role", "admin")
    print(f"Indexed admins: {indexed_admins}")

    admins_full = users.find_by_index_with_data("role", "admin")
    print(f"Indexed admins with data: {list(admins_full.keys())}")

    users.drop_index("role")
    print(f"Indexes after drop: {users.list_indexes()}")

    # ── SWITCH OPERATIONS ────────────────────

    print("\n--- Switch Operations ---")
    print(f"Current: {users}")

    # Switch collection
    sessions = users.switch_collection("sessions")
    print(f"Switched col: {sessions}")

    # Switch database
    other_db = users.switch_database("otherdb")
    print(f"Switched db:  {other_db}")

    # Switch both
    logs = users.switch(database="analytics", collection="logs")
    print(f"Switched both: {logs}")

    # ── IMPORT / EXPORT — JSON ────────────────

    print("\n--- Export / Import JSON ---")
    users.export_json("/tmp/mongo_users_export.json")
    print("Exported to /tmp/mongo_users_export.json")

    json_str = users.export_json_string()
    print(f"JSON string length: {len(json_str)} chars")

    # Import into a fresh collection
    users_import = MongoUtil(database="myapp", collection="users_imported")
    users_import.delete_all()
    imported = users_import.import_json("/tmp/mongo_users_export.json", overwrite=True)
    print(f"Imported: {imported} entries into users_imported")
    print(f"Imported count: {users_import.count_all()}")

    # Import from string
    users_import.delete_all()
    imported2 = users_import.import_json_string(json_str, overwrite=True)
    print(f"Imported from string: {imported2} entries")

    # ── IMPORT / EXPORT — CSV ─────────────────

    print("\n--- Export / Import CSV ---")
    users.export_csv("/tmp/mongo_users_export.csv")
    print("Exported to /tmp/mongo_users_export.csv")

    csv_str = users.export_csv_string()
    print(f"CSV string:\n{csv_str}")

    users_csv_import = MongoUtil(database="myapp", collection="users_csv_imported")
    users_csv_import.delete_all()
    imported_csv = users_csv_import.import_csv("/tmp/mongo_users_export.csv", overwrite=True)
    print(f"Imported from CSV: {imported_csv} entries")

    # ── TTL EXAMPLE ──────────────────────────

    print("\n--- TTL Example ---")
    otps = MongoUtil(
        database="myapp",
        collection="otps",
        default_ttl=300,  # 5 minutes
    )
    otps.delete_all()
    otps.create({"code": "482917", "user_id": "u1"}, id="otp_123")
    otps.create({"code": "938172", "user_id": "u2"}, id="otp_456")
    print(f"OTP entries: {otps.count_all()}")
    print("(These will auto-delete after 5 minutes via MongoDB TTL index)")

    # expire without default_ttl
    temp = MongoUtil(database="myapp", collection="temp_cache")
    temp.delete_all()
    temp.create({"key": "temp_data"}, id="temp_001")
    temp.expire("temp_001", 10)
    print(f"Temp doc — will expire ~10s: {temp.read('temp_001') is not None}")

    # ── REMOVE DUPLICATES ────────────────────

    print("\n--- Remove Duplicates ---")
    dedup_test = MongoUtil(database="myapp", collection="dedup_test")
    dedup_test.delete_all()
    dedup_test.create({"email": "a@x.com", "name": "Alice"}, id="d1")
    dedup_test.create({"email": "a@x.com", "name": "Alice"}, id="d2")   # duplicate
    dedup_test.create({"email": "b@x.com", "name": "Bob"},   id="d3")
    dedup_test.create({"email": "b@x.com", "name": "Bob"},   id="d4")   # duplicate
    dedup_test.create({"email": "b@x.com", "name": "Bob"},   id="d5")   # duplicate
    dedup_test.create({"email": "c@x.com", "name": "Charlie"}, id="d6")
    print(f"Before dedup: {dedup_test.count_all()} docs")

    report = dedup_test.remove_duplicates(query={"email": 1}, dry_run=True)
    print(f"Dry run report: {report}")

    report = dedup_test.remove_duplicates(query={"email": 1})
    print(f"After dedup: {report}")
    print(f"Final count: {dedup_test.count_all()} docs")

    # ── DROP COLLECTION / DATABASE ───────────

    print("\n--- Drop Operations ---")
    print(f"Collections before drop: {users.list_collections()}")
    print("(drop_collection / drop_database available but skipped in demo to preserve data)")

    # ── CLEANUP ───────────────────────────────

    print("\n--- Cleanup ---")
    users.delete_all()
    users_import.delete_all()
    users_csv_import.delete_all()
    otps.delete_all()
    sessions.delete_all()
    temp.delete_all()
    dedup_test.delete_all()
    print(f"Users remaining:        {users.count_all()}")
    print(f"Imported remaining:     {users_import.count_all()}")
    print(f"CSV Imported remaining: {users_csv_import.count_all()}")
    print(f"OTPs remaining:         {otps.count_all()}")
    users.close()
    users_import.close()
    users_csv_import.close()
    otps.close()
    sessions.close()
    temp.close()
    dedup_test.close()
    print("\nDone!")
